var namespace_apache_1_1_ignite_1_1_core =
[
    [ "Binary", "namespace_apache_1_1_ignite_1_1_core_1_1_binary.html", "namespace_apache_1_1_ignite_1_1_core_1_1_binary" ],
    [ "Cache", "namespace_apache_1_1_ignite_1_1_core_1_1_cache.html", "namespace_apache_1_1_ignite_1_1_core_1_1_cache" ],
    [ "Cluster", "namespace_apache_1_1_ignite_1_1_core_1_1_cluster.html", "namespace_apache_1_1_ignite_1_1_core_1_1_cluster" ],
    [ "Common", "namespace_apache_1_1_ignite_1_1_core_1_1_common.html", "namespace_apache_1_1_ignite_1_1_core_1_1_common" ],
    [ "Communication", "namespace_apache_1_1_ignite_1_1_core_1_1_communication.html", "namespace_apache_1_1_ignite_1_1_core_1_1_communication" ],
    [ "Compute", "namespace_apache_1_1_ignite_1_1_core_1_1_compute.html", "namespace_apache_1_1_ignite_1_1_core_1_1_compute" ],
    [ "Configuration", "namespace_apache_1_1_ignite_1_1_core_1_1_configuration.html", "namespace_apache_1_1_ignite_1_1_core_1_1_configuration" ],
    [ "Datastream", "namespace_apache_1_1_ignite_1_1_core_1_1_datastream.html", "namespace_apache_1_1_ignite_1_1_core_1_1_datastream" ],
    [ "DataStructures", "namespace_apache_1_1_ignite_1_1_core_1_1_data_structures.html", "namespace_apache_1_1_ignite_1_1_core_1_1_data_structures" ],
    [ "Discovery", "namespace_apache_1_1_ignite_1_1_core_1_1_discovery.html", "namespace_apache_1_1_ignite_1_1_core_1_1_discovery" ],
    [ "Events", "namespace_apache_1_1_ignite_1_1_core_1_1_events.html", "namespace_apache_1_1_ignite_1_1_core_1_1_events" ],
    [ "Interop", "namespace_apache_1_1_ignite_1_1_core_1_1_interop.html", "namespace_apache_1_1_ignite_1_1_core_1_1_interop" ],
    [ "Lifecycle", "namespace_apache_1_1_ignite_1_1_core_1_1_lifecycle.html", "namespace_apache_1_1_ignite_1_1_core_1_1_lifecycle" ],
    [ "Log", "namespace_apache_1_1_ignite_1_1_core_1_1_log.html", "namespace_apache_1_1_ignite_1_1_core_1_1_log" ],
    [ "Messaging", "namespace_apache_1_1_ignite_1_1_core_1_1_messaging.html", "namespace_apache_1_1_ignite_1_1_core_1_1_messaging" ],
    [ "PersistentStore", "namespace_apache_1_1_ignite_1_1_core_1_1_persistent_store.html", "namespace_apache_1_1_ignite_1_1_core_1_1_persistent_store" ],
    [ "Plugin", "namespace_apache_1_1_ignite_1_1_core_1_1_plugin.html", "namespace_apache_1_1_ignite_1_1_core_1_1_plugin" ],
    [ "Resource", "namespace_apache_1_1_ignite_1_1_core_1_1_resource.html", "namespace_apache_1_1_ignite_1_1_core_1_1_resource" ],
    [ "Services", "namespace_apache_1_1_ignite_1_1_core_1_1_services.html", "namespace_apache_1_1_ignite_1_1_core_1_1_services" ],
    [ "Transactions", "namespace_apache_1_1_ignite_1_1_core_1_1_transactions.html", "namespace_apache_1_1_ignite_1_1_core_1_1_transactions" ],
    [ "IgniteConfiguration", "class_apache_1_1_ignite_1_1_core_1_1_ignite_configuration.html", "class_apache_1_1_ignite_1_1_core_1_1_ignite_configuration" ],
    [ "IgniteConfigurationSection", "class_apache_1_1_ignite_1_1_core_1_1_ignite_configuration_section.html", "class_apache_1_1_ignite_1_1_core_1_1_ignite_configuration_section" ],
    [ "Ignition", "class_apache_1_1_ignite_1_1_core_1_1_ignition.html", "class_apache_1_1_ignite_1_1_core_1_1_ignition" ],
    [ "IIgnite", "interface_apache_1_1_ignite_1_1_core_1_1_i_ignite.html", "interface_apache_1_1_ignite_1_1_core_1_1_i_ignite" ]
];