= Apache Ignite Documentation
:toc:
:toc-title:

== Overview
This directory contains the source files, HTML templates and css styles used to integrate the Apache Ignite documentation into this website. The original Apache Ignite documentation is maintained in the same repository as the code base (https://github.com/apache/ignite), in the "/docs" subdirectory. The `build.sh` script pulls the asciidoc files from that repo and builds them with custom templates/styles


== Building the Docs Locally

To build the docs locally, you can install `jekyll` and other dependencies on your machine.

=== Install Jekyll and Asciidoctor

. Install Jekyll by following this instruction:  https://jekyllrb.com/docs/installation/[window=_blank]
. In the “/docs” directory, run the following command:
+
[source, shell]
----
$ bundle
----
+
This should install all dependencies, including `asciidoctor`.
. Build the docs:
+
[source, shell]
----
$ ./build.sh --github-branch=IGNITE-7595 --version=2.8.1
----
This will compile the docs and move the built files to /docs/ in the website root dir.
+
. 
To test the docs:
+
[source, shell]
----
$ ./build.sh --github-branch=IGNITE-7595 --version=2.8.1 --serve
----

The command compiles the Asciidoc files into HTML pages and starts a local webserver.

Open `http://localhost:4000/docs[window=_blank]` in your browser.

