var searchData=
[
  ['cache',['Cache',['../classignite_1_1cache_1_1Cache.html',1,'ignite::cache']]],
  ['cacheaffinity',['CacheAffinity',['../classignite_1_1cache_1_1CacheAffinity.html',1,'ignite::cache']]],
  ['cacheclient',['CacheClient',['../classignite_1_1thin_1_1cache_1_1CacheClient.html',1,'ignite::thin::cache']]],
  ['cacheentry',['CacheEntry',['../classignite_1_1cache_1_1CacheEntry.html',1,'ignite::cache']]],
  ['cacheentryevent',['CacheEntryEvent',['../classignite_1_1cache_1_1CacheEntryEvent.html',1,'ignite::cache']]],
  ['cacheentryeventfilter',['CacheEntryEventFilter',['../classignite_1_1cache_1_1event_1_1CacheEntryEventFilter.html',1,'ignite::cache::event']]],
  ['cacheentryeventfilterholder',['CacheEntryEventFilterHolder',['../classignite_1_1impl_1_1cache_1_1event_1_1CacheEntryEventFilterHolder.html',1,'ignite::impl::cache::event']]],
  ['cacheentryeventlistener',['CacheEntryEventListener',['../classignite_1_1cache_1_1event_1_1CacheEntryEventListener.html',1,'ignite::cache::event']]],
  ['cacheentryprocessor',['CacheEntryProcessor',['../classignite_1_1cache_1_1CacheEntryProcessor.html',1,'ignite::cache']]],
  ['cachepeekmode',['CachePeekMode',['../structignite_1_1thin_1_1cache_1_1CachePeekMode.html',1,'ignite::thin::cache::CachePeekMode'],['../structignite_1_1cache_1_1CachePeekMode.html',1,'ignite::cache::CachePeekMode']]],
  ['clienttransaction',['ClientTransaction',['../classignite_1_1thin_1_1transactions_1_1ClientTransaction.html',1,'ignite::thin::transactions']]],
  ['clienttransactions',['ClientTransactions',['../classignite_1_1thin_1_1transactions_1_1ClientTransactions.html',1,'ignite::thin::transactions']]],
  ['clustergroup',['ClusterGroup',['../classignite_1_1cluster_1_1ClusterGroup.html',1,'ignite::cluster']]],
  ['clusternode',['ClusterNode',['../classignite_1_1cluster_1_1ClusterNode.html',1,'ignite::cluster']]],
  ['collectiontype',['CollectionType',['../structignite_1_1binary_1_1CollectionType.html',1,'ignite::binary']]],
  ['compute',['Compute',['../classignite_1_1compute_1_1Compute.html',1,'ignite::compute']]],
  ['computefunc',['ComputeFunc',['../classignite_1_1compute_1_1ComputeFunc.html',1,'ignite::compute']]],
  ['constreference',['ConstReference',['../classignite_1_1ConstReference.html',1,'ignite']]],
  ['continuousquery',['ContinuousQuery',['../classignite_1_1cache_1_1query_1_1continuous_1_1ContinuousQuery.html',1,'ignite::cache::query::continuous']]],
  ['continuousqueryhandle',['ContinuousQueryHandle',['../classignite_1_1cache_1_1query_1_1continuous_1_1ContinuousQueryHandle.html',1,'ignite::cache::query::continuous']]]
];
